try notarize

diff --git a/.github/workflows/mac-build.yaml b/.github/workflows/mac-build.yaml
--- a/.github/workflows/mac-build.yaml
+++ b/.github/workflows/mac-build.yaml
@@ -23,7 +23,10 @@ jobs:
         APPLICATION_CERTIFICATES_BASE64: ${{ secrets.APPLE_APPLICATION_CERTIFICATES_BASE64 }}
         CERTIFICATES_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}     
         KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
-        SIGNER: ${{ secrets.APPLE_SIGNER }}
+        SIGNER: ${{ secrets.APPLE_SIGNER }}     
+        APPLE_ID: ${{ secrets.APPLE_ID }}
+        APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_API_PASSWORD }}
+        TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}        
       run: |
         # create variables
         APPLICATION_CERTIFICATE_PATH=$RUNNER_TEMP/application_certificates.p12
@@ -42,6 +45,9 @@ jobs:
         security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
         security list-keychain -d user -s $KEYCHAIN_PATH
         
+        # add notary password
+        xcrun notarytool store-credentials --apple-id "$APPLE_ID" --password "$APP_SPECIFIC_PASSWORD" --team-id "$TEAM_ID" "my-notary-profile"
+        
     - name: Build BIT package
       run: |
         mkdir build
@@ -56,6 +62,22 @@ jobs:
       run: |   
         # sign
         codesign -s "$SIGNER" -v --deep build/BEAGLE-BIT-4.1.0-Darwin.pkg
+              
+   - name: Notarize BIT package
+      run: |
+        # Submit for notarization
+        REQUEST_UUID=$(xcrun notarytool submit "build/BEAGLE-BIT-4.1.0-Darwin.pkg" --keychain-profile "my-notary-profile" --wait | grep "id:" | awk '{print $2}')
+
+        # Check notarization status and staple
+        if [[ -n "$REQUEST_UUID" ]]; then
+          echo "Notarization submitted with UUID: $REQUEST_UUID"
+          xcrun notarytool log "$REQUEST_UUID" --keychain-profile "my-notary-profile"
+          xcrun stapler staple "build/BEAGLE-BIT-4.1.0-Darwin.pkg"
+          echo "Notarization successful and stapled."
+        else
+          echo "Notarization submission failed."
+          exit 1
+        fi              
                  
     - name: Upload BIT package
       if: always()
